manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pfilipp
      url-base: https://github.com/pfilipp
    - name: infely
      url-base: https://github.com/infely
    - name: xkonni
      url-base: https://github.com/xkonni
    - name: tokyo2006
      url-base: https://github.com/tokyo2006
    - name: englmaxi
      url-base: https://github.com/englmaxi
  projects:
    - name: zmk
      remote: pfilipp
      revision: layer-state-report
      import: app/west.yml
    - name: nice-view-battery
      remote: infely
      revision: main
    - name: nice-view-glyphs
      remote: xkonni
      revision: main
    - name: prospector-zmk-module
      remote: tokyo2006
      revision: nice_nano_spi2
    - name: zmk-dongle-display
      remote: englmaxi
      revision: v0.3
  self:
    path: config
