name: Build Eyelash Sofle Dongle firmware

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "boards/arm/eyelash_sofle/**"
      - "boards/shields/eyeslash_sofle_dongle/**"
      - "build_eyelash_sofle_dongle.yaml"
      - "config/behaviors.dtsi"
      - "config/key-labels/eyelash_sofle.h"
      - "config/eyelash_sofle.*"
      - "zephyr/**"
    tags:
      - "build"
permissions:
  contents: write

jobs:
  build:
    name: Build Eyelash Sofle Dongle
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      build_matrix_path: build_eyelash_sofle_dongle.yaml
      archive_name: eyelash-sofle-dongle-firmware
